### ISSUE TITLE
[GROUP] Add SMS center settings

### ISSUE THREAD

**Issue by thewizardplusplus** [thewizardplusplus/wizard-sms-emulator#11]
- [x] ~~#16 &mdash; add default SMS center;~~
- [x] ~~#17 &mdash; add showing flag of SMS center editor;~~
- [x] ~~#25 &mdash; use default SMS center settings.~~
