### ISSUE TITLE
[GROUP] Add autocompletion into SMS form

### ISSUE THREAD

**Issue by thewizardplusplus** [thewizardplusplus/wizard-sms-emulator#12]
- [x] ~~#18 &mdash; save a SMS data in Shared Preferences on sending;~~
- [x] ~~#19 &mdash; restore a SMS data from Shared Preferences on the SMS form creation;~~
- [x] ~~#20 &mdash; add the SMS form autocompletion flag.~~
